#!/bin/bash

echo "Enter two numbers:"
read a
read b

echo "Menu:"
echo "1. Addition"
echo "2. Subtraction"
echo "3. Multiplication"
echo "4. Division"
echo "Enter your choice:"
read choice

case $choice in
    1)
        result=$((a + b))
        echo "Addition = $result"
        ;;
    2)
        result=$((a - b))
        echo "Subtraction = $result"
        ;;
    3)
        result=$((a * b))
        echo "Multiplication = $result"
        ;;
    4)
        if [ $b -ne 0 ]
        then
            result=$((a / b))
            echo "Division = $result"
        else
            echo "Division by zero not allowed"
        fi
        ;;
    *)
        echo "Invalid choice"
        ;;
esac









#!/bin/bash
echo "Enter the option"
echo "a=print the date"
echo "b=list all files in current directory"
read choice
case $choice in
a) data;;
b) ls;;
*) note a valid option 
esac

