#!/bin/bash

for i in 1 2 3
do
    echo "Number is $i"
done

echo
echo "Second Method"

for j in "Symbiosis Institute of Technology Nagpur"
do
    echo "Institute name is $j"
done


!/bin/bash

for i in {1..5}
do
    echo "Number: $i"
done


!/bin/bash

i=1
while [ $i -le 5 ]
do
    echo "Number: $i"
    ((i++))
done


!/bin/bash

i=1
until [ $i -gt 5 ]
do
    echo "Number: $i"
    ((i++))
done


!/bin/bash

echo "Enter a number:"
read n

i=1
sum=0

while [ $i -le $n ]
do
    sum=$((sum + i))
    ((i++))
done

echo "Sum of first $n numbers is: $sum"


#!/bin/bash

echo "Enter a number:"
read n

for i in {1..10}
do
    echo "$n x $i = $((n * i))"
done


#!/bin/bash

echo "Enter number:"
read n

for ((i=2; i*i<=n; i++))
do
    if (( n % i == 0 ))
    then
        echo "Not Prime"
        exit
    fi
done

echo "Prime"


!/bin/bash

echo "Enter a number:"
read n

fact=1

for ((i=1; i<=n; i++))
do
    fact=$((fact * i))
done

echo "Factorial of $n is: $fact"
